using System.CodeDom.Compiler;
using JetBrains.Annotations;

namespace PdbToCSharp.Lang.Cs;

public sealed class CsWriters(CsGen gen) : LangWriters(gen) {
  public override CsGen Gen => (CsGen)base.Gen;
  private readonly Dictionary<string, IndentedTextWriter> _writerMap = [];
  private readonly Dictionary<CsStructure, IndentedTextWriter> _derivedMap = [];
  private readonly List<IndentedTextWriter> _miscWriters = [];
  private IndentedTextWriter? _classNs;
  private IndentedTextWriter? _enumNs;
  private IndentedTextWriter? _unionNs;
  private IndentedTextWriter? _templateClassNs;
  private IndentedTextWriter? _templateUnionNs;
  private IndentedTextWriter? _arrayNs; // Inline arrays
  private IndentedTextWriter? _globalsWriter;
  private IndentedTextWriter? _globalFunctionsWriter;
  private readonly string _moduleTypeName = gen.Namespace.Replace(".", "") + "Module";
  private readonly string _outputTypePath = Path.Join(gen.OutputPath, "/Types");
  private readonly string _outputHookPath = Path.Join(gen.OutputPath, "/Hooks");
  private readonly string _outputGlobalHookPath = Path.Join(gen.OutputPath, "/GlobalHooks");

  // Lazy loading ensures none of these create files if there are no types that would be written to them.
  private IndentedTextWriter ClassWriter => _classNs ??= CreateWriter("_Root_Classes", _outputTypePath);
  public IndentedTextWriter InlineArrayWriter => _arrayNs ??= CreateWriter("_Root_InlineArrays", _outputTypePath);
  private IndentedTextWriter EnumWriter => _enumNs ??= CreateWriter("_Root_Enums", _outputTypePath);
  private IndentedTextWriter UnionWriter => _unionNs ??= CreateWriter("_Root_Unions", _outputTypePath);

  private IndentedTextWriter TemplateClassWriter =>
    _templateClassNs ??= CreateWriter("_Root_TemplateClasses", _outputTypePath);

  private IndentedTextWriter TemplateUnionWriter =>
    _templateUnionNs ??= CreateWriter("_Root_TemplateUnions", _outputTypePath);

  public IndentedTextWriter GlobalsWriter =>
    _globalsWriter ??= CreateWriter("GlobalFields", OutputPath);

  public IndentedTextWriter GlobalFunctionsWriter =>
    _globalFunctionsWriter ??= CreateWriter("GlobalFunctions", OutputPath, includeNamespace: false);

  public IndentedTextWriter GetMatching(LangType type) {
    if (type is not CsUdt udt) {
      throw new ArgumentException($"Type {type} is not a CsUdt");
    }

    IndentedTextWriter? writer;
    if (udt is CsStructure csStructure) {
      foreach (CsBaseClass baseClass in csStructure.BaseClasses) {
        if (_derivedMap.TryGetValue(baseClass.BaseType, out writer)) {
          _derivedMap[csStructure] = writer;
          return writer;
        }
      }

      bool shouldCreateDerivedFile = csStructure.DerivedTypes.Count > 5 &&
        csStructure.SelfName.Length < 32 &&
        csStructure.FullName.Length < 64 &&
        !csStructure.FullName.Any(char.IsNumber);

      if (shouldCreateDerivedFile) {
        if (_derivedMap.TryGetValue(csStructure, out writer)) {
          return writer;
        }

        string ns = csStructure.Namespace is not null ? csStructure.Namespace.Replace('.', '_') + "_" : "_Root.";
        string fileName = "_derived." + ns + csStructure.FullName;

        writer = CreateWriter(fileName, _outputTypePath, csStructure.Namespace);
        _derivedMap[csStructure] = writer;

        return writer;
      }
    }

    string? csNamespace = udt.Namespace;
    if (csNamespace is not null) {
      if (_writerMap.TryGetValue(csNamespace, out writer)) {
        return writer;
      }

      writer = CreateWriter(csNamespace.Replace('.', '_'), _outputTypePath, csNamespace);
      _writerMap[csNamespace] = writer;

      return writer;
    }

    string origName = udt.Record.Name.String;
    if (udt is CsEnum) {
      return EnumWriter;
    }

    if (origName.Contains('<')) {
      return udt is CsUnion ? TemplateUnionWriter : TemplateClassWriter;
    }

    return udt is CsUnion ? UnionWriter : ClassWriter;
  }

  public void CreateModuleFile() {
    string path = Path.Join(Gen.NativeModPath, "NativeModule.g.cs");
    string funcOffset = Gen.Reader.PdbFile.DbiStream.SectionHeaders[0].VirtualAddress.ToString();

    Directory.CreateDirectory(Gen.NativeModPath);
    using StreamWriter streamWriter = new(path);
    using IndentedTextWriter writer = new(streamWriter);
    writer.WriteLine(AutoGeneratedNotice);
    writer.WriteLine("namespace NativeMod;");
    writer.WriteLine();
    writer.WriteLine("/// <summary>");
    writer.WriteLine("/// Provides access to the base function and memory addresses of the C++ game.");
    writer.WriteLine("/// </summary>");
    writer.WriteGeneratedCodeAttribute(prependGlobal: true);
    writer.Write("public static class NativeModule");
    using (writer.BracedScope()) {
      writer.WriteLine("/// <summary>");
      writer.WriteLine("/// Gets the base function address of the C++ game.");
      writer.WriteLine("/// </summary>");
      writer.WriteLine("public static ulong FunctionAddress => MemoryAddress + _functionOffset;");
      writer.WriteLine();
      writer.WriteLine("/// <summary>");
      writer.WriteLine("/// Gets or sets the base memory address of the C++ game.");
      writer.WriteLine("/// </summary>");
      writer.WriteLine("/// <remarks>");
      writer.WriteLine("/// This value should be set by the mod loader or a modding API before any mods are loaded.");
      writer.WriteLine("/// </remarks>");
      writer.WriteLine("/// <exception cref=\"InvalidOperationException\">");
      writer.WriteLine("/// Thrown if the memory address is read before it is set.");
      writer.WriteLine("/// </exception>");
      writer.Write("public static ulong MemoryAddress");
      using (writer.BracedScope()) {
        writer.WriteMany(
          "get => _address != 0",
          " ? _address",
          " : throw new InvalidOperationException(\"ModLoader must set MemoryAddress before it is read\");"
        );
        writer.WriteLine();
        writer.WriteLine("set => _address = value;");
      }

      writer.WriteLine();
      writer.WriteLine("private static ulong _address;");
      writer.WriteMany("private const ulong _functionOffset = ", funcOffset, ";");
      writer.WriteLine();
    }
  }

  private IndentedTextWriter CreateWriter(string fileName, string path, string? csNamespaceName = null,
    bool includeNamespace = true) {
    if (fileName == "_") {
      fileName = "anonymous";
    }

    Directory.CreateDirectory(path);
    string fullPath = Path.Join(path, fileName.Replace("@", "") + ".g.cs");
    IndentedTextWriter writer = new(new StreamWriter(fullPath));
    writer.WriteLine(AutoGeneratedNotice);
    writer.WriteLine(AttributeUsings);
    writer.WriteLine(CppAliases);

    if (includeNamespace) {
      writer.Write("namespace ");
      writer.Write(Namespace);
      if (csNamespaceName is not null) {
        writer.Write('.');
        writer.Write(csNamespaceName);
      }

      writer.WriteLine(';');
      writer.WriteLine();
    }

    return writer;
  }

  public IndentedTextWriter CreateNewWriter(string fileName, string path, string? csNamespaceName = null,
    bool includeNamespace = true) {
    IndentedTextWriter writer = CreateWriter(fileName, path, csNamespaceName, includeNamespace);
    _miscWriters.Add(writer);
    return writer;
  }

  [MustDisposeResource]
  public IndentedTextWriter CreateGlobalHookWriter(string? path, string name) {
    string finalDir = Path.Join(_outputGlobalHookPath, path?.Replace('.', '/').Replace("@", "") ?? "_root");
    Directory.CreateDirectory(finalDir);
    string fullPath = Path.Join(finalDir, name + ".g.cs");
    IndentedTextWriter writer = new(new StreamWriter(fullPath));
    WriteHookWriterStart(writer, "GlobalFunctions" + (path is not null ? "." + path : ""));
    return writer;
  }

  public IndentedTextWriter CreateHookWriter(string fullName, string? csNamespaceName, out bool mustDispose) {
    IndentedTextWriter? writer;
    string finalDir = Path.Join(_outputHookPath, csNamespaceName?.Replace('.', '/').Replace("@", "") ?? "_root");
    if (fullName.Length + (csNamespaceName?.Length ?? 0) > 48) {
      mustDispose = false;
      if (_longTypeNameWriter.TryGetValue(finalDir, out writer)) {
        return writer;
      }

      Directory.CreateDirectory(finalDir);
      writer = new IndentedTextWriter(new StreamWriter(Path.Join(finalDir, "__longtypename.g.cs")));
      _longTypeNameWriter[finalDir] = writer;
      _miscWriters.Add(writer);
      WriteHookWriterStart(writer, csNamespaceName);
      return writer;
    }

    mustDispose = true;
    Directory.CreateDirectory(finalDir);
    string fullPath = Path.Join(finalDir, fullName + ".g.cs");
    writer = new IndentedTextWriter(new StreamWriter(fullPath));
    WriteHookWriterStart(writer, csNamespaceName);
    return writer;
  }

  private void WriteHookWriterStart(IndentedTextWriter w, string? ns) {
    w.WriteLine(AutoGeneratedNotice);
    w.Write(AttributeUsings);
    w.WriteLine("using System.Runtime.CompilerServices;");
    w.WriteLine();
    w.WriteLine("using NativeMod;");
    w.WriteLine();
    w.WriteLine(CppAliases);
    w.WriteLine();
    w.Write("namespace On.");
    w.Write(Namespace);
    if (ns is not null) {
      w.Write('.');
      w.Write(ns.SanitizeName());
    }

    w.WriteLine(';');
    w.WriteLine();
    w.WriteLine("#nullable enable");
    w.WriteLine();
  }

  private readonly Dictionary<string, IndentedTextWriter> _longTypeNameWriter = [];

  public override void Dispose() {
    _classNs?.Flush();
    _arrayNs?.Flush();
    _enumNs?.Flush();
    _unionNs?.Flush();
    _templateClassNs?.Flush();
    _templateUnionNs?.Flush();
    _globalsWriter?.Flush();
    _globalFunctionsWriter?.Flush();

    Parallel.ForEach(_writerMap.Values, writer => writer.Flush());
    Parallel.ForEach(_derivedMap.Values, writer => writer.Flush());
    Parallel.ForEach(_miscWriters, writer => writer.Flush());

    _classNs?.Dispose();
    _arrayNs?.Dispose();
    _enumNs?.Dispose();
    _unionNs?.Dispose();
    _templateClassNs?.Dispose();
    _templateUnionNs?.Dispose();
    _globalsWriter?.Dispose();
    _globalFunctionsWriter?.Dispose();
    foreach (IndentedTextWriter writer in _writerMap.Values) {
      writer.Dispose();
    }

    foreach (IndentedTextWriter writer in _derivedMap.Values) {
      writer.Dispose();
    }

    foreach (IndentedTextWriter writer in _miscWriters) {
      writer.Dispose();
    }
  }

  private const string AutoGeneratedNotice =
    """
    // <auto-generated>
    // This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files of C++ apps.
    // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
    // </auto-generated>

    """;

  private const string AttributeUsings =
    """
    using System.Runtime.InteropServices;
    using System.CodeDom.Compiler;

    """;

  private const string CppAliases =
    """
    using CppHResult = uint;

    // 1 byte char values
    using unsigned_char = byte;
    using _char = sbyte;
    using signed_char = sbyte;

    // 2 byte char values
    using char16_t = ushort;
    using wchar_t = ushort;

    // 4 byte char values
    using char32_t = uint;
    
    """ +
//     """
//     using CppInt8 = sbyte;
//     using CppUInt8 = byte;
//
//     // 2 byte integer values
//     using CppInt16 = short;
//     using CppUInt16 = ushort;
//     using CppInt16Short = short;
//     using CppUInt16Short = ushort;
//
//     // 4 byte integer values
//     using CppInt32 = int;
//     using CppUInt32 = uint;
//     using CppInt32Long = int;
//     using CppUInt32Long = uint;
//
//     // 8 byte integer values
//     using CppInt64 = long;
//     using CppUInt64 = ulong;
//     using CppInt64Quad = long;
//     using CppUInt64Quad = ulong;
//     """ +
    """
    
    // 16 byte integer values
    using int128_t = System.Int128;
    using uint128_t = System.UInt128;
    using __int128 = System.Int128;
    using unsigned___int128 = System.UInt128;

    // 4 byte float values
    using CppFloat32PartialPrecision = float;

    // complex float values
    using CppComplex128 = System.Numerics.Complex;
    
    """ +
    // """
    //     // boolean values
    //     using CppBoolean16 = ushort;
    //     using CppBoolean32 = uint;
    //     using CppBoolean64 = ulong;
    //     using CppBoolean128 = System.UInt128;
    // """ +
    "";
}
