using System.CodeDom.Compiler;
using PdbToCSharp.Types;

namespace PdbToCSharp;

using Writer = IndentedTextWriter;

internal sealed class CsWriters(SourceGen sourceGen, string outputPath, string namespaceName) : IDisposable {
  private readonly Dictionary<string, Writer> _writerMap = [];
  private readonly Dictionary<CsStructure, Writer> _derivedMap = [];
  private Writer? _classNs;
  private Writer? _enumNs;
  private Writer? _unionNs;
  private Writer? _templateClassNs;
  private Writer? _templateUnionNs;
  private Writer? _arrayNs; // Inline arrays
  private Writer? _globalsWriter;
  private readonly string _moduleName = namespaceName.Replace(".", "") + "Module";

  // Lazy loading ensures none of these create files if there are no types that would be written to them.
  private Writer ClassWriter => _classNs ??= CreateWriter("_Root_Classes");
  public Writer InlineArrayWriter => _arrayNs ??= CreateWriter("_Root_InlineArrays");
  private Writer EnumWriter => _enumNs ??= CreateWriter("_Root_Enums");
  private Writer UnionWriter => _unionNs ??= CreateWriter("_Root_Unions");
  private Writer TemplateClassWriter => _templateClassNs ??= CreateWriter("_Root_TemplateClasses");
  private Writer TemplateUnionWriter => _templateUnionNs ??= CreateWriter("_Root_TemplateUnions");

  public Writer GlobalsWriter => _globalsWriter ??= CreateWriter("_Globals");

  public Writer GetMatching(CsUdt udt) {
    Writer? writer;
    if (udt is CsStructure csStructure) {
      foreach (CsBaseClass baseClass in csStructure.BaseClasses) {
        if (_derivedMap.TryGetValue(baseClass.BaseType, out writer)) {
          _derivedMap[csStructure] = writer;
          return writer;
        }
      }

      bool shouldCreateDerivedFile = csStructure.DerivedTypes.Count > 5 &&
        csStructure.SelfName.Length < 32 &&
        csStructure.FullName.Length < 64;

      if (shouldCreateDerivedFile) {
        if (_derivedMap.TryGetValue(csStructure, out writer)) {
          return writer;
        }

        string ns = csStructure.Namespace is not null ? csStructure.Namespace.Replace('.', '_') + "_" : "_Root.";
        string fileName = "_derived." + ns + csStructure.FullName;

        writer = CreateWriter(fileName, csStructure.Namespace);
        _derivedMap[csStructure] = writer;

        return writer;
      }
    }

    string? csNamespace = udt.Namespace;
    if (csNamespace is not null) {
      if (_writerMap.TryGetValue(csNamespace, out writer)) {
        return writer;
      }

      writer = CreateWriter(csNamespace.Replace('.', '_'), csNamespace);
      _writerMap[csNamespace] = writer;

      return writer;
    }

    string origName = udt.Record.Name.String;
    if (udt is CsEnum) {
      return EnumWriter;
    }

    if (origName.Contains('<')) {
      return udt is CsUnion ? TemplateUnionWriter : TemplateClassWriter;
    }

    return udt is CsUnion ? UnionWriter : ClassWriter;
  }

  public void CreateModuleFile() {
    string path = Path.Join(outputPath, "_Module.generated.cs");
    using StreamWriter streamWriter = new(path);
    using Writer writer = new(streamWriter);
    writer.WriteLine(AutoGeneratedNotice);
    writer.Write("namespace ");
    writer.Write(namespaceName);
    writer.WriteLine(';');
    writer.WriteLine();
    writer.WriteGeneratedCodeAttribute(prependGlobal: true);
    writer.Write("public static class ");
    writer.Write(_moduleName);
    writer.WriteLine(" {");
    writer.Indent++;
    writer.Write("public static ulong ");
    writer.Write(sourceGen.FunctionAddressFieldName);
    writer.Write(" => ");
    writer.Write(sourceGen.MemoryAddressFieldName);
    writer.Write(" + ");
    writer.WriteLine("_functionOffset;");
    writer.WriteLine();
    writer.Write("public static ulong ");
    writer.Write(sourceGen.MemoryAddressFieldName);
    writer.WriteLine(" {");
    writer.Indent++;
    writer.WriteLine(
      "get => _address != 0 ? _address : throw new InvalidOperationException(\"Must set field before reading\");");
    writer.WriteLine("set => _address = value;");
    writer.Indent--;
    writer.WriteLine('}');
    writer.WriteLine();
    writer.WriteLine("private static ulong _address;");
    writer.Write("private static readonly ulong _functionOffset = ");
    writer.Write(GetFunctionOffset());
    writer.WriteLine(';');
    writer.Indent--;
    writer.WriteLine('}');
    return;

    uint GetFunctionOffset() {
      // Offset of ".text" section in the PDB file
      return sourceGen.Pdb.PdbFile.DbiStream.SectionHeaders[0].VirtualAddress;
    }
  }

  private Writer CreateWriter(string fileName, string? csNamespaceName = null, bool includeStaticModuleRef = true) {
    if (fileName == "_") {
      fileName = "anonymous";
    }

    string fullPath = Path.Join(outputPath, fileName.Replace("@", "") + ".generated.cs");
    Writer writer = new(new StreamWriter(fullPath));
    writer.WriteLine(AutoGeneratedNotice);
    writer.WriteLine(AttributeUsings);
    writer.WriteLine(CppAliases);

    if (includeStaticModuleRef) {
      writer.Write("using static ");
      writer.Write(namespaceName);
      writer.Write('.');
      writer.Write(_moduleName);
      writer.WriteLine(';');
    }

    writer.Write("namespace ");
    writer.Write(namespaceName);
    if (csNamespaceName is not null) {
      writer.Write('.');
      writer.Write(csNamespaceName);
    }

    writer.WriteLine(';');
    writer.WriteLine();
    return writer;
  }

  public void Dispose() {
    _classNs?.Flush();
    _arrayNs?.Flush();
    _enumNs?.Flush();
    _unionNs?.Flush();
    _templateClassNs?.Flush();
    _templateUnionNs?.Flush();
    _globalsWriter?.Flush();
    foreach (Writer writer in _writerMap.Values) {
      writer.Flush();
    }

    foreach (Writer writer in _derivedMap.Values) {
      writer.Flush();
    }

    _classNs?.Dispose();
    _arrayNs?.Dispose();
    _enumNs?.Dispose();
    _unionNs?.Dispose();
    _templateClassNs?.Dispose();
    _templateUnionNs?.Dispose();
    _globalsWriter?.Dispose();
    foreach (Writer writer in _writerMap.Values) {
      writer.Dispose();
    }

    foreach (Writer writer in _derivedMap.Values) {
      writer.Dispose();
    }
  }

  private const string AutoGeneratedNotice =
    """
    // <auto-generated>
    // This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
    // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
    // </auto-generated>

    """;

  private const string AttributeUsings =
    """
    using System.Runtime.InteropServices;
    using System.CodeDom.Compiler;

    """;

  private const string CppAliases =
    """
    using CppHResult = uint;

    // 1 byte char values
    using CppUnsignedChar = byte;
    using CppChar = sbyte;
    using CppSignedChar = sbyte;

    // 2 byte char values
    using CppChar16 = ushort;
    using CppWideChar = ushort;

    // 4 byte char values
    using CppChar32 = uint;

    using CppInt8 = sbyte;
    using CppUInt8 = byte;

    // 2 byte integer values
    using CppInt16 = short;
    using CppUInt16 = ushort;
    using CppInt16Short = short;
    using CppUInt16Short = ushort;

    // 4 byte integer values
    using CppInt32 = int;
    using CppUInt32 = uint;
    using CppInt32Long = int;
    using CppUInt32Long = uint;

    // 8 byte integer values
    using CppInt64 = long;
    using CppUInt64 = ulong;
    using CppInt64Quad = long;
    using CppUInt64Quad = ulong;

    // 16 byte integer values
    using CppInt128 = System.Int128;
    using CppUInt128 = System.UInt128;
    using CppInt128Oct = System.Int128;
    using CppUInt128Oct = System.UInt128;

    // 4 byte float values
    using CppFloat32PartialPrecision = float;

    // complex float values
    using CppComplex128 = System.Numerics.Complex;

    // boolean values
    using CppBoolean16 = ushort;
    using CppBoolean32 = uint;
    using CppBoolean64 = ulong;
    using CppBoolean128 = System.UInt128;

    """;
}
