using System.CodeDom.Compiler;
using PdbToCSharp.Types;

namespace PdbToCSharp;

using Writer = IndentedTextWriter;

internal sealed class CsWriters(string outputPath, string namespaceName) : IDisposable {
  private readonly Dictionary<string, Writer> _namespaceMap = [];
  private Writer? _classNs;
  private Writer? _enumNs;
  private Writer? _unionNs;
  private Writer? _templateClassNs;
  private Writer? _templateUnionNs;
  private Writer? _arrayNs; // Inline arrays

  // Lazy loading ensures none of these create files if there are no types that would be written to them.
  private Writer ClassWriter => _classNs ??= CreateWriter("Generated__Root_Classes.cs");
  public Writer InlineArrayWriter => _arrayNs ??= CreateWriter("Generated__Root_InlineArrays.cs");
  private Writer EnumWriter => _enumNs ??= CreateWriter("Generated__Root_Enums.cs");
  private Writer UnionWriter => _unionNs ??= CreateWriter("Generated__Root_Unions.cs");
  private Writer TemplateClassWriter => _templateClassNs ??= CreateWriter("Generated__Root_TemplateClasses.cs");
  private Writer TemplateUnionWriter => _templateUnionNs ??= CreateWriter("Generated__Root_TemplateUnions.cs");

  public Writer GetMatching(CsUdt udt) {
    string? csNamespace = udt.Namespace;
    if (csNamespace is not null) {
      if (_namespaceMap.TryGetValue(csNamespace, out Writer? writer)) {
        return writer;
      }

      writer = CreateWriter($"Generated_{csNamespace.Replace('.', '_')}.cs", csNamespace);
      _namespaceMap[csNamespace] = writer;

      return writer;
    }

    string origName = udt.Record.Name.String;
    if (udt is CsEnum) {
      return EnumWriter;
    }

    string? name = udt.Namespace;
    if (name is null) {
      return udt is CsUnion ? UnionWriter : ClassWriter;
    }

    if (origName.Contains('<')) {
      return udt is CsUnion ? TemplateUnionWriter : TemplateClassWriter;
    }

    return udt is CsUnion ? UnionWriter : ClassWriter;
  }

  private Writer CreateWriter(string path, string? csNamespaceName = null) {
    string fullPath = Path.Join(outputPath, path);
    Writer writer = new(new StreamWriter(fullPath));
    writer.WriteLine(WriterStart);
    writer.Write("namespace ");
    writer.Write(namespaceName);
    if (csNamespaceName is not null) {
      writer.Write('.');
      writer.Write(csNamespaceName);
    }
    writer.WriteLine(';');
    writer.WriteLine();
    return writer;
  }

  public void Dispose() {
    _classNs?.Flush();
    _arrayNs?.Flush();
    _enumNs?.Flush();
    _unionNs?.Flush();
    _templateClassNs?.Flush();
    _templateUnionNs?.Flush();
    foreach (Writer writer in _namespaceMap.Values) {
      writer.Flush();
    }

    _classNs?.Dispose();
    _arrayNs?.Dispose();
    _enumNs?.Dispose();
    _unionNs?.Dispose();
    _templateClassNs?.Dispose();
    _templateUnionNs?.Dispose();
    foreach (Writer writer in _namespaceMap.Values) {
      writer.Dispose();
    }
  }

  private const string WriterStart =
    """
    // <auto-generated>
    // This code was generated by PdbToCSharp, a tool that generates C# bindings from PDB files.
    // Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
    // </auto-generated>
    
    #pragma warning disable
    
    using System.CodeDom.Compiler;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;
    
    """;
}
